services:
  zikula_ezcomments_module.container.link_container:
    class: Zikula\EZCommentsModule\Container\LinkContainer
    arguments:
      - "@translator.default"
      - "@router"
      - "@zikula_permissions_module.api.permission"
    tags:
      - { name: zikula.link_container }

  zikula_ezcomments_module.form.config_type:
    class: Zikula\EZCommentsModule\Form\Config
    arguments:
      - "@translator.default"
    tags:
      - { name: form.type }

  zikula_ezcomments_module.hook_provider.ui_hooks_hooks_provider:
    class: Zikula\EZCommentsModule\HookProvider\UiHooksProvider
    arguments:
      - '@translator.default'
      - '@zikula_permissions_module.api.permission'
      - '@templating'
      - '@doctrine.orm.entity_manager'
      - '@request_stack'
      - "@router"
      - "@zikula_extensions_module.api.variable"
      - "@zikula_users_module.current_user"
    tags:
    - { name: zikula.hook_provider, areaName: "provider.zikulaezcommentsmodule.ui_hooks.ezcomments" }