services:
  zikula_ezcomments_module.container.link_container:
    class: Zikula\EZCommentsModule\Container\LinkContainer
    arguments:
      - "@translator.default"
      - "@router"
      - "@zikula_permissions_module.api.permission"
    tags:
      - { name: zikula.link_container }

  zikula_ezcomments_module.form.comment_type:
    class: Zikula\EZCommentsModule\Form\Comment
    arguments:
      - "@translator.default"
      - "@zikula_settings_module.locale_api"
    tags:
      - { name: form.type }

  zikula_ezcomments_module.hook_provider.ui_hooks_hooks_provider:
          class: Zikula\EZCommentsModule\HookProvider\UiHooksProvider
          arguments:
            - '@translator.default'
            - '@zikula_permissions_module.api.permission'
            - '@templating'
            - '@doctrine.orm.entity_manager'
            - '@request_stack'
          tags:
          - { name: zikula.hook_provider, areaName: "provider.zikulaezcommentsmodule.ui_hooks.ezcomments" }