services:
  zikula_ezcomments_module.container.link_container:
    class: Zikula\EZCommentsModule\Container\LinkContainer
    arguments:
      - "@translator.default"
      - "@router"
      - "@zikula_permissions_module.api.permission"
    tags:
      - { name: zikula.link_container }

  zikula_ezcomments_module.form.comment_type:
    class: Zikula\EZCommentsModule\Form\Comment
    arguments:
      - "@translator.default"
      - "@zikula_settings_module.locale_api"
    tags:
      - { name: form.type }